### ISSUE TITLE
static methods not allowed in dart extension as far as I can tell

### ISSUE THREAD

**Issue by derek-pavao** [graphicbeacon/source_gen_demo#1]
This demo doesn't work quite like I was expecting, unless I'm missing something.

when defining a static method in a `extension on SomeClass` block, that static method is on the extension it self, not the `on-type` being extended.

My assumption was that with the SerializeGenerator portion of this demo you'd be able to call `Order.fromJson()` in the example.

**Comment by graphicbeacon** [comment]
That's how it works. You are adding the methods on the extension, which will be available on the type as long as the file with the extension is imported.

**Comment by derek-pavao** [comment]
If that's the case, I'm not sure why I get this error then.
<img width="842" alt="source_gen_demo____Desktop_source_gen_demo__–_____example_usage_lib_main_dart" src="https://user-images.githubusercontent.com/1998134/120649516-d8de3f80-c44a-11eb-9368-9f87e5e7ba94.png">

**Comment by graphicbeacon** [comment]
@derek-pavao You need to reference the extension by name:

```dart
final order = $OrderSerializer.fromJson({
  'name': 'My Order',
  'price': '2.00',
});
```

**Comment by derek-pavao** [comment]
oh, got it.

That's too bad the static method doesn't get added to the class similar to how the instance method does. Thanks for clearing that up for me.
